name: "LLM Analysis Action"
description: "Analyzes legislative bills using LLM for summarization and change tracking"

inputs:
  state:
    description: "State to analyze"
    required: true
    default: "wy"
  analyze-versions:
    description: "Analyze bill versions and track changes"
    required: false
    default: "true"
  generate-reports:
    description: "Generate human-readable reports"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber click requests

    - name: Set up OpenAI API Key
      shell: bash
      run: |
        if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
          echo "Using repository secret API key"
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        else
          echo "No API key provided - will run in mock mode"
        fi

    - name: Run LLM Bill Analysis
      shell: bash
      run: |
        echo "ðŸ¤– Starting LLM Bill Analysis"
        echo "State: ${{ inputs.state }}"
        echo "Analyze versions: ${{ inputs.analyze-versions }}"
        echo "Generate reports: ${{ inputs.generate-reports }}"

        # Run analysis for the specified state
        if [ "${{ inputs.state }}" = "all" ]; then
          echo "ðŸ“„ Analyzing all available states..."
          # TODO: Add logic for analyzing all states
        else
          echo "ðŸ“„ Analyzing bills for state: ${{ inputs.state }}"

                          # Check if data_processed exists (from state repository)
        if [ -d "data_output/data_processed" ]; then
          echo "ðŸ“„ Found data_processed directory, analyzing bills for state: ${{ inputs.state }}"

          # Run analysis on the processed data
          python openstates_scraped_data_formatter/cli_bill_tracker.py analyze \
            --show-summary \
            --verbose \
            --output "${STATE}_llm_analysis_$(date +%Y%m%d_%H%M%S).json"

          echo "âœ… ${{ inputs.state }} analysis complete"
        elif [ -d "sample_data" ]; then
          echo "ðŸ“„ Found sample data, analyzing for testing..."

          python openstates_scraped_data_formatter/cli_bill_tracker.py analyze \
            --show-summary \
            --verbose \
            --output "${STATE}_sample_analysis_$(date +%Y%m%d_%H%M%S).json"

          echo "âœ… ${{ inputs.state }} sample analysis complete"
        else
          echo "âš ï¸ No data found - neither data_output/data_processed nor sample_data"
          echo "ðŸ“ Available directories:"
          ls -la
        fi
        fi

        fi

    - name: Upload analysis reports
      uses: actions/upload-artifact@v4
      if: inputs.generate-reports == 'true'
      with:
        name: llm-analysis-reports-${{ github.run_id }}
        path: |
          *.json
          llm_analysis_results.json
          wyoming_bill_tracker_report.json
        retention-days: 30

    - name: Generate summary
      shell: bash
      run: |
        echo "ðŸ“Š LLM Analysis Summary"
        echo "========================"
        echo "Run ID: ${{ github.run_id }}"
        echo "State: ${{ inputs.state }}"
        echo "Timestamp: $(date)"
        echo ""
        echo "Reports generated:"
        ls -la *.json 2>/dev/null || echo "No JSON reports found"
        echo ""
        echo "Artifacts available for download"
