name: "OpenCivicData Pipeline Router"
description: "Routes to scraping or text extraction actions"

inputs:
  action-type:
    description: "Type of action: 'scrape' or 'extract'"
    required: true
    default: "extract"
  state:
    description: "State to process (2-letter abbreviation)"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  use-scrape-cache:
    description: "Use cache for scraping (scrape only)"
    required: false
    default: "false"
  force-update:
    description: "Force push changes even if there are upstream changes"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Validate action type
      shell: bash
      run: |
        if [ "${{ inputs.action-type }}" != "scrape" ] && [ "${{ inputs.action-type }}" != "extract" ]; then
          echo "❌ Error: Invalid action-type. Must be 'scrape' or 'extract'"
          exit 1
        fi
        echo "✅ Action type validated: ${{ inputs.action-type }}"

    - name: Route to Scraping Action
      if: inputs.action-type == 'scrape'
      uses: ./actions/scrape
      with:
        state: ${{ inputs.state }}
        github-token: ${{ inputs.github-token }}
        use-scrape-cache: ${{ inputs.use-scrape-cache }}
        force-update: ${{ inputs.force-update }}

    - name: Route to Text Extraction Action
      if: inputs.action-type == 'extract'
      uses: ./actions/extract
      with:
        state: ${{ inputs.state }}
        github-token: ${{ inputs.github-token }}
        force-update: ${{ inputs.force-update }}
