# Example caller workflow for text extraction
# Copy this to your state data repo as .github/workflows/extract-text.yml

name: Text Extraction from Bills

on:
  schedule:
    - cron: "0 4 * * *" # Daily at 4 AM UTC (adjust as needed)
  workflow_dispatch:

jobs:
  extract-text:
    name: Text Extraction
    runs-on: ubuntu-latest
    timeout-minutes: 355 # ~5.9 hours (close to GitHub's 6-hour limit, allows graceful shutdown)
    permissions:
      contents: write
    outputs:
      timeout-triggered: ${{ steps.extract.outputs.timeout-triggered }}

    steps:
      - name: Checkout state repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run text extraction action
        id: extract
        uses: windy-civi/toolkit/actions/extract@refactor/v2-data-structure
        with:
          state: wy # ⚠️ UPDATE THIS: Change to your state code (e.g., wy, usa, il, tx)
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-update: "false"

      - name: Display extraction summary
        if: always()
        shell: bash
        run: |
          echo "📊 Text Extraction Summary"
          echo "================================"
          echo "✅ Check country:us/state:*/sessions/*/bills/*/files/ for extracted text files"
          echo "📄 Look for *_extracted.txt files in the files/ directories"
          echo ""
          echo "ℹ️  Features:"
          echo "  - Incremental processing (skips already-processed bills)"
          echo "  - Auto-saves progress every 30 minutes"
          echo "  - Graceful shutdown with final commit on timeout"
          echo "  - Can be safely restarted if timeout occurs"

  # Auto-restart job if it timed out (work incomplete)
  restart-if-timeout:
    name: Restart if Timed Out
    needs: extract-text
    runs-on: ubuntu-latest
    if: needs.extract-text.outputs.timeout-triggered == 'true'
    permissions:
      actions: write

    steps:
      - name: Trigger workflow restart
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "⚠️ Previous run hit timeout. Restarting to continue extraction..."
          gh workflow run extract-text.yml --repo ${{ github.repository }}
