# Example workflow for caller repos using the split actions
# Copy this to your caller repo's .github/workflows/scrape-and-format-data.yml
# and update the state parameter as needed

name: Scrape and Format Data

on:
  workflow_dispatch:
    inputs:
      use-scrape-cache:
        type: boolean
        description: Use OpenStates scraper cache
        default: false
      force-update:
        type: boolean
        description: "Force push even if upstream changed (use with caution)"
        default: false

jobs:
  scrape:
    name: "🕷️ Scrape Data"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      scrape-artifact-name: ${{ steps.scrape.outputs.scrape-artifact-name }}
      scrape-tarball-path: ${{ steps.scrape.outputs.scrape-tarball-path }}
      manifest-path: ${{ steps.scrape.outputs.manifest-path }}

    steps:
      - name: Checkout state repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run scraper action
        id: scrape
        uses: windy-civi/opencivicdata-blockchain-transformer/actions/scrape@main
        with:
          state: usa # ⚠️ UPDATE THIS: Change to your state code (e.g., 'wy', 'usa', 'il', 'tx')
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-scrape-cache: ${{ inputs.use-scrape-cache }}

      # Note: The scrape action automatically uploads the artifact internally,
      # so we don't need to upload it again here

  format:
    name: "📝 Format Data"
    runs-on: ubuntu-latest
    needs: scrape
    permissions:
      contents: write

    steps:
      - name: Checkout state repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download scrape artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.scrape.outputs.scrape-artifact-name }}

      - name: Run formatter action
        uses: windy-civi/opencivicdata-blockchain-transformer/actions/format@main
        with:
          state: wy # ⚠️ UPDATE THIS: Change to your state code (e.g., 'wy', 'usa', 'il', 'tx')
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scrape-artifact-name: ${{ needs.scrape.outputs.scrape-artifact-name }}
          force-update: ${{ inputs.force-update }}
